apiVersion: v1
kind: Secret
metadata:
  name: {{ include "networkops.fullname" . }}-secrets
  labels:
    {{- include "networkops.labels" . | nindent 4 }}
type: Opaque
stringData:
  DEVICE_USERNAME: {{ .Values.devices.username | quote }}
  DEVICE_PASSWORD: {{ .Values.devices.password | quote }}
  {{- if .Values.redis.enabled }}
  REDIS_URL: {{ include "networkops.redisUrl" . | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ include "networkops.postgresUrl" . | quote }}
  {{- end }}
  {{- if .Values.netbox.enabled }}
  NETBOX_API_TOKEN: {{ .Values.netbox.apiToken | quote }}
  {{- end }}
