all:
  children:
    cisco_routers:
      hosts:
        R1:
          ansible_host: 10.255.255.11
          ansible_network_os: cisco.ios.ios
          ansible_connection: ansible.netcommon.network_cli
        R2:
          ansible_host: 10.255.255.12
          ansible_network_os: cisco.ios.ios
          ansible_connection: ansible.netcommon.network_cli
        R3:
          ansible_host: 10.255.255.13
          ansible_network_os: cisco.ios.ios
          ansible_connection: ansible.netcommon.network_cli
        R4:
          ansible_host: 10.255.255.14
          ansible_network_os: cisco.ios.ios
          ansible_connection: ansible.netcommon.network_cli
    cisco_switches:
      hosts:
        Switch-R1:
          ansible_host: 10.255.255.21
          ansible_network_os: cisco.ios.ios
          ansible_connection: ansible.netcommon.network_cli
        Switch-R2:
          ansible_host: 10.255.255.22
          ansible_network_os: cisco.ios.ios
          ansible_connection: ansible.netcommon.network_cli
        Switch-R4:
          ansible_host: 10.255.255.24
          ansible_network_os: cisco.ios.ios
          ansible_connection: ansible.netcommon.network_cli
    linux_hosts:
      hosts:
        Alpine-1:
          ansible_host: 10.255.255.110
          ansible_connection: ssh
    containerlab:
      hosts:
        spine1:
          ansible_host: 172.20.20.10
          ansible_connection: local
          containerlab_type: srlinux
          container_name: clab-datacenter-spine1
        edge1:
          ansible_host: 172.20.20.5
          ansible_connection: local
          containerlab_type: frr
          container_name: clab-datacenter-edge1
        R9:
          ansible_host: 172.20.20.3
          ansible_connection: local
          containerlab_type: frr
          container_name: clab-datacenter-R9
        R10:
          ansible_host: 172.20.20.4
          ansible_connection: local
          containerlab_type: frr
          container_name: clab-datacenter-R10
        server1:
          ansible_host: 10.100.1.10
          ansible_connection: local
          containerlab_type: linux
          container_name: clab-datacenter-server1
        server2:
          ansible_host: 10.100.2.10
          ansible_connection: local
          containerlab_type: linux
          container_name: clab-datacenter-server2
      vars:
        containerlab_vm: containerlab
